"""Remove redundant document_chunks table

Revision ID: bdfe03bbd3d5
Revises: 74c1f94e3e35
Create Date: 2025-10-21 11:44:54.950109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfe03bbd3d5'
down_revision = '74c1f94e3e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_chunks_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    # ### end Alembic commands ###
