"""Add owner_id to models

Revision ID: g2h3i4j5k6l7
Revises: f1a2b3c4d5e6
Create Date: 2025-10-25 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g2h3i4j5k6l7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add owner_id column to documents table
    op.add_column('documents', sa.Column('owner_id', sa.String(length=255), nullable=True))
    
    # Add owner_id column to requirements table
    op.add_column('requirements', sa.Column('owner_id', sa.String(length=255), nullable=True))
    
    # Add owner_id column to project_summaries table
    op.add_column('project_summaries', sa.Column('owner_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove owner_id column from project_summaries table
    op.drop_column('project_summaries', 'owner_id')
    
    # Remove owner_id column from requirements table
    op.drop_column('requirements', 'owner_id')
    
    # Remove owner_id column from documents table
    op.drop_column('documents', 'owner_id')
    # ### end Alembic commands ###